services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=3000
    # Команда для запуску через nodemon, щоб зміни в коді підтягувалися відразу
    command: npx nodemon index.js --host 0.0.0.0 --port 3000 --cache ./my_cache